
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SWZIM_WEBWeb
{

using System;
    using System.Collections.Generic;
    
public partial class Events
{

    public Events()
    {

        this.Groups = new HashSet<Groups>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public int AddedBy { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public string Description { get; set; }

    public int EventTypeId { get; set; }



    public virtual EventTypes EventTypes { get; set; }

    public virtual Users Users { get; set; }

    public virtual ICollection<Groups> Groups { get; set; }

}

}
