
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SWZIM_WEBWeb
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
public partial class Events
{

    public Events()
    {

        this.Groups = new HashSet<Groups>();

    }

    public int Id { get; set; }

    [DisplayName("Nazwa")]
    public string Name { get; set; }

    [DisplayName("Szer. geo.")]
    public decimal Latitude { get; set; }

    [DisplayName("D³. geo")]
    public decimal Longitude { get; set; }

    [DisplayName("Doda³/a")]
    public int AddedBy { get; set; }

    [DisplayName("Czas utworzenia")]
    public System.DateTime CreatedAt { get; set; }

    [DisplayName("Opis")]
    public string Description { get; set; }

    [DisplayName("Typ")]
    public int EventTypeId { get; set; }

    [DisplayName("Status")]
    public int Status { get; set; }



    public virtual EventTypes EventTypes { get; set; }

    public virtual Users Users { get; set; }

    public virtual ICollection<Groups> Groups { get; set; }

}

}
