
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SWZIM_WEBWeb
{

using System;
    using System.Collections.Generic;
    
public partial class Layers
{

    public Layers()
    {

        this.LayoutElements = new HashSet<LayoutElements>();

        this.Events = new HashSet<Events>();

        this.Groups = new HashSet<Groups>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }



    public virtual ICollection<LayoutElements> LayoutElements { get; set; }

    public virtual ICollection<Events> Events { get; set; }

    public virtual ICollection<Groups> Groups { get; set; }

}

}
