//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZIM_WEBWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string Label { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsGroup { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
